sudo: required
services:
  - docker
before_install:
  - docker build -t chandu/dockerreact -f Dockerfile.dev .
script:
  - docker run chandu/dockerreact npm run test -- --coverage # coverage is used to autmoatically exit the test suite without waiting for user input
