sudo: required
services:
  - docker
before_install:
  - docker build -t chandu/dockerreact -f Dockerfile.dev .
script:
  - docker run chandu/dockerreact npm run test -- --coverage # coverage is used to autmoatically exit the test suite without waiting for user input
deploy: #everything here is from ebs from aws
  provider: elasticbeanstalk
  region: "us-west-2"
  app: <nameofappinelasiticbeanstalk>
  env: "Docker-env" # from ebs
  bucket_name: <name of the s3 bucket that is created by ebs>
  bucket_path: "nameofappinelasiticbeanstalk"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY # stored in travis ci
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
